import os
import streamlit as st
from supabase import create_client

# Correct Page Config for Mobile Viewports
st.set_page_config(page_title="7-AI Trading Core", layout="centered", initial_sidebar_state="collapsed")

# Database Token Exchange
supabase = create_client(os.getenv("SUPABASE_URL"), os.getenv("SUPABASE_KEY"))

st.title("⚡ 7-AI Trading Consensus Core")
st.caption("Live 15M Matrix Signal Deployment Center")

# Fetch Latest 5 Signals From Cloud Database
try:
    res = supabase.table("signals").select("*").order("created_at", desc=True).limit(5).execute()
    signals = res.data
except Exception as e:
    st.error(f"Database Connectivity Offline: {str(e)}")
    signals = []

if not signals:
    st.info("Waiting for next 15M cron execution cycle...")

for sig in signals:
    with st.expander(f"📊 {sig['pair']} — {sig['final_decision']}", expanded=True):
        # Color coding metrics based on final decision matrix
        if sig['final_decision'] == "BUY":
            st.success(f"Final Execution: {sig['final_decision']}")
        elif sig['final_decision'] == "SELL":
            st.error(f"Final Execution: {sig['final_decision']}")
        else:
            st.warning(f"Final Execution: {sig['final_decision']}")
            
        # Extract corresponding sub-votes generated by 7 AIs
        v_res = supabase.table("ai_votes").select("*").eq("signal_id", sig['id']).execute()
        votes = v_res.data
        
        st.write("**Individual AI Node Breakdown:**")
        for vote in votes:
            col1, col2 = st.columns([1, 3])
            with col1:
                st.markdown(f"`{vote['ai_name']}`")
            with col2:
                st.markdown(f"**{vote['vote']}** ({vote['confidence']}% Confidence)")
                st.caption(f"*Reason:* {vote['reasoning']}")
    st.divider()
    
